// <auto-generated />
namespace ProjectManag.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Login_info : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Login_info));
        
        string IMigrationMetadata.Id
        {
            get { return "202003171800476_Login_info"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
